#pragma once
#define RGBLIGHT_LAYERS
#define ENCODER_RESOLUTION 4
// #define RGB_MATRIX_KEYPRESSES
// #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING
// #define RGB_MATRIX_STARTUP_MODE RGB_MATRIX_SPLASH
