#pragma once
#define TAP_TERM_KEYS_ENABLE
#define RETRO_TAPPING_PER_KEY
#define BOOTMAGIC_KEY_SALT KC_TAB

// #define BILATERAL_COMBINATIONS 200

//#define PERMISSIVE_HOLD
//#define IGNORE_MOD_TAP_INTERRUPT
// #define IGNORE_MOD_TAP_INTERRUPT_PER_KEY
#define HOLD_ON_OTHER_KEY_PRESS_PER_KEY

#define TAPPING_TERM 190
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD_PER_KEY
#define TAPPING_FORCE_HOLD_PER_KEY
#define QUICK_TAP_TERM 100
#define QUICK_TAP_TERM_PER_KEY

#define TAPPING_TOGGLE 5

#define COMBO_COUNT 3

// #define COMBO_TERM 60

#define OLED_FONT_H "users/yanghu/glcdfont2.c"

